version: '3.8'

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    ports:
      - "8004:8004"

  alerts:
    build:
      context: .
      dockerfile: Dockerfile.alerts
    ports:
      - "8002:8002"

  news:
    build:
      context: .
      dockerfile: Dockerfile.news
    ports:
      - "8001:8001"

  price:
    build:
      context: .
      dockerfile: Dockerfile.price
    ports:
      - "8000:8000"

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html 