version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - price
      - news
      - alerts
      - agent
    networks:
      - intellifi-network

  price:
    build:
      context: .
      dockerfile: Dockerfile.price
    ports:
      - "8000:8000"
    networks:
      - intellifi-network

  news:
    build:
      context: .
      dockerfile: Dockerfile.news
    ports:
      - "8001:8001"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
    networks:
      - intellifi-network

  alerts:
    build:
      context: .
      dockerfile: Dockerfile.alerts
    ports:
      - "8002:8002"
    networks:
      - intellifi-network

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    ports:
      - "8003:8003"
    depends_on:
      - price
      - news
      - alerts
    networks:
      - intellifi-network

  exsat-node:
    image: exsat-network/exsat-node:latest
    ports:
      - "9876:9876"
      - "8888:8888"
      - "8999:8999"
    volumes:
      - exsat-data:/var/lib/exsat
    networks:
      - intellifi-network

networks:
  intellifi-network:
    driver: bridge

volumes:
  exsat-data: 